nelmio_api_doc:
    documentation:
        paths:
            /api/tokens:
                post:
                    operationId: 'api_post_tokens_new'
                    tags:
                        - Authentication
                    summary: 'Retrieves the token authentication.'
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    ref: '#/components/schemas/User-write'
                                example:
                                    email: 'client@bilemo.fr'
                                    password: 'bilemo'
                    responses:
                        200:
                            description: 'Creates the token and returns it'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                readOnly: true
                        400:
                            description: 'Bad Request'
                        401:
                            description: 'Invalid Credentials'
                        405:
                            description: 'Method Not Allowed'
            /api/products:
                get:
                    operationId: 'api_get_products_list'
                    tags:
                        - Products
                    security:
                        - Bearer: [ ]
                    summary: 'Retrieves the collection of Product resources.'
                    parameters:
                        - ref: '#/components/parameters/page'
                        - ref: '#/components/parameters/order'
                        - ref: '#/components/parameters/filter'
                    responses:
                        200:
                            description: 'Product collection'
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: object
                                            ref: '#/components/schemas/Product-read'

                        401:
                            description: 'Unauthorized'
                        404:
                            description: 'Page Not Found'
                        405:
                            description: 'Method Not Allowed'
            /api/products/{id}:
                get:
                    operationId: 'api_get_products_show'
                    tags:
                        - Products
                    security:
                        -   Bearer: [ ]
                    summary: 'Retrieves of Product resource.'
                    responses:
                        200:
                            description: 'Product resource'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        ref: '#/components/schemas/Product-read'

                        401:
                            description: 'Unauthorized'
                        404:
                            description: 'Resource Not Found'
                        405:
                            description: 'Method Not Allowed'
            /api/users:
                get:
                    operationId: 'api_get_users_list'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Retrieves the collection of User resources.'
                    parameters:
                        -   ref: '#/components/parameters/page'
                        -   ref: '#/components/parameters/order'
                        -   ref: '#/components/parameters/filter'
                    responses:
                        200:
                            description: 'User collection'
                            content:
                                application/json:
                                    schema:
                                        type: array
                                        items:
                                            type: object
                                            ref: '#/components/schemas/User-read'

                        401:
                            description: 'Unauthorized'
                        404:
                            description: 'Page Not Found'
                        405:
                            description: 'Method Not Allowed'
                post:
                    operationId: 'api_post_users_new'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Creates a User resource.'
                    requestBody:
                        required: true
                        description: The new User resource
                        content:
                            application/json:
                                schema:
                                    type: object
                                    ref: '#/components/schemas/User-write'
                    responses:
                        201:
                            description: 'User ressource'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        ref: '#/components/schemas/User-read'
                        400:
                            description: 'Invalid Input'
                        401:
                            description: 'Unauthorized'
                        405:
                            description: 'Method Not Allowed'
                        415:
                            description: 'Unsupported Media Type'
                        422:
                            description: 'Unprocessable Entity'
            /api/users/{id}:
                get:
                    operationId: 'api_get_users_show'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Retrieves of User resource.'
                    responses:
                        200:
                            description: 'User resource'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        ref: '#/components/schemas/User-read'
                        401:
                            description: 'Unauthorized'
                        403:
                            description: 'Forbidden'
                        404:
                            description: 'Resource Not Found'
                        405:
                            description: 'Method Not Allowed'
                put:
                    operationId: 'api_put_users_replace'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Replaces the User resource'
                    requestBody:
                        required: true
                        description: The updated User resource
                        content:
                            application/json:
                                schema:
                                    type: object
                                    ref: '#/components/schemas/User-write'
                    responses:
                        200:
                            description: 'User resource replaced'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        ref: '#/components/schemas/User-read'
                        400:
                            description: 'Invalid Input'
                        401:
                            description: 'Unauthorized'
                        403:
                            description: 'Forbidden'
                        405:
                            description: 'Method Not Allowed'
                        404:
                            description: 'Resource Not Found'
                        415:
                            description: 'Unsupported Media Type'
                        422:
                            description: 'Unprocessable Entity'
                patch:
                    operationId: 'api_put_users_update'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Updates the User resource'
                    requestBody:
                        required: true
                        description: The updated User resource
                        content:
                            application/json:
                                schema:
                                    type: object
                                    ref: '#/components/schemas/User-write'
                    responses:
                        200:
                            description: 'User resource updated'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        ref: '#/components/schemas/User-read'
                        400:
                            description: 'Invalid Input'
                        401:
                            description: 'Unauthorized'
                        403:
                            description: 'Forbidden'
                        405:
                            description: 'Method Not Allowed'
                        404:
                            description: 'Resource Not Found'
                        415:
                            description: 'Unsupported Media Type'
                        422:
                            description: 'Unprocessable Entity'
                delete:
                    operationId: 'api_delete_users_remove'
                    tags:
                        - Users
                    security:
                        -   Bearer: [ ]
                    summary: 'Removes the User resource.'
                    responses:
                        204:
                            description: 'Resource deleted'
                        401:
                            description: 'Unauthorized'
                        403:
                            description: 'Forbidden'
                        404:
                            description: 'Resource Not Found'
                        405:
                            description: 'Method Not Allowed'
        tags:
            - name: 'Authentication'
            - name: 'Products'
            - name: 'Users'
